# Generated by Django 6.1.1 on 2026-09-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_bibliotecario_leitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bibliotecario',
        ),
        migrations.DeleteModel(
            name='Leitor',
        ),
    ]
